version: '3.4'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - trena-redis:/data
    ports:
      - '6379:6379'
    expose:
      - '6379'

  external-translator:
    image: trena-external-translator:0.1.1
    depends_on:
      - redis
    restart: always
    tty: true
    ports:
      - '3000:3000'
    expose:
      - '3000'
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULL_TRANSLATION_RUNNER_PARALLELISM=5
      - BULL_TRANSLATION_RUNNER_HEADLESS=true
      - BULL_TRANSLATION_RUNNER_USE_PROXY=true
      - BULL_TRANSLATION_RUNNER_PROXY_LIST_FILE_PATH=/usr/local/app/deploy/proxy-list.txt
      - BULL_TRANSLATION_RUNNER_COUNT_UNIT_TO_CHECK_FAILED=10
      - BULL_TRANSLATION_CONCURRENCY=10
    links:
      - redis
    volumes:
      - ./:/usr/local/app/deploy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  trena-redis:
